blogTitle = "evan nichols"
authorName = "evan nichols"
authorDetail = "I like software and the outdoors. EngRes @ Google NYC."
linkPrefix = ""
googleAnalyticsId = "UA-69960811-1"
syntaxTheme = "atom-one-dark"
twitterId = ""
facebookId = ""
githubId = "e-nichols"
