blogTitle = "evan nichols"
authorName = "evan nichols"
authorDetail = "Software Developer. Outdoor enthusiast. EngRes @ GoogleNYC."
linkPrefix = ""
googleAnalyticsId = "UA-69960811-1"
syntaxTheme = "atom-one-dark"
twitterId = ""
facebookId = ""
githubId = "e-nichols"
